---
title: "Workshop2"
author: "afidums"
date: "2026-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# Making sure packages are loaded
library(tidyverse)
library(palmerpenguins)
library(lubridate)

# The messy metadata provided by your colleague
island_metadata <- tibble(
  island_name = c(" biscoe", "Dream ", "Torgersen"),
  station_install = c("15/01/2003", "22-03-2004", "05/11/2001"),
  latitude = c(-64.81, -64.73, -64.76)
)

print(island_metadata)
#loading in penguins dataset 
penguins <- palmerpenguins::penguins

#2.11 
#Excerise 1 
#making clean_metadata from island metadata by changing island_name to island and adjusting the station_install with to date objects
clean_metadata <- island_metadata %>%
  mutate(station_install = dmy(station_install)) %>%  #changes the station_install column to date objects using dmy function from lubridate package 
  mutate (island_name = str_trim(island_name)) %>% #removes whitespace from island_name column
  mutate(island_name = str_to_title(island_name))#changes the first letter of each word in island_name column to uppercase

print(clean_metadata)

#Excerise 2 - Relational Join
#joining clean meta data to the main penguins dataset 
penguins_spatial <- penguins |> left_join(clean_metadata, by = join_by(island == island_name))

#checking to see the new columns were added correctly 
head(penguins_spatial)

#Excerise 3 - The Wide Summary Matrix 
#Using penguins_spatial dataset, removing all missing values in body_mass_g, grouping by species and island, and summarising the data to find the maximum body mass (max()) and then pivoting the dataset wider so that the species form rows and the islands form the columns 

penguins_summary <- penguins_spatial %>%
  filter(!is.na(body_mass_g)) %>% #removes all missing values in body_mass_g column
  group_by(species, island) %>% #groups the data by species and island
  summarise(max_body_mass = max(body_mass_g), .groups = "drop") %>% #summarises the data to find the maximum body mass for each group
  pivot_wider(names_from = island, values_from = max_body_mass) #pivots the dataset wider so that the species form rows and the islands form the columns

#checking the summary
penguins_summary
```

```{r}
#2.12
#Phase 1
#loading the data in

library(readxl)
estuary_catch_log <- read_excel("../data/workshop2/estuary_catch_log.xlsx")
#combining all the pages of estuary_catch_log into one dataset
sheets <- excel_sheets("../data/workshop2/estuary_catch_log.xlsx")
estuary_catch_log <- map_dfr(sheets, ~ read_excel("../data/workshop2/estuary_catch_log.xlsx", sheet = .x))

#changing estuary_catch_long site column to factor 
estuary_catch_log <- estuary_catch_log %>% mutate(site = as.factor(site))

#changing site names with stringr 
estuary_catch_log_clean <- estuary_catch_log |>
  mutate(
    # 1. Convert everything to lowercase
    site = str_to_lower(site),
    # 2. Replace any spaces with underscores
    site = str_replace_all(site, pattern = " ", replacement = "_"),
    # 3. Trim any leading or trailing whitespace (invisible spaces at the ends)
    site = str_trim(site)
  )
estuary_catch_log_clean

#changing date to date objects
estuary_catch_log_clean <- estuary_catch_log_clean %>% mutate(date = ymd(date))

#changing date to date objects in the sonde dataset 
sonde <- read_csv("../data/workshop2/estuary_sonde_data.csv")
sonde <- sonde %>% mutate(true_time = dmy_hm(timestamp))

#converting hardware error (-999 turbidity) in sonde to NA values 
sonde <- sonde |> mutate(turbidity = na_if(turbidity, -999))

#changing MANGROVE JACK to mangrove_jack
estuary_catch_log_clean <- estuary_catch_log_clean %>% mutate(species = recode(species, "MANGROVE JACK" = "mangrove_jack"))

#Phase 2 
#summerising sonde data - creating a daily summary table that calculates the mean temperature and salinity for each site on each day 

summarised_sonde <- sonde %>%
  group_by(site, date = as.Date(true_time)) %>% #grouping by site and date 
  summarise(mean_temp = mean(temperature, na.rm = TRUE), #calculating mean temperature for each site on each day 
            mean_salinity = mean(salinity, na.rm = TRUE), #calculating mean salinity for each site on each day 
            .groups = "drop") #ungrouping the data

#using mutating join to merge species_dictonary into catch data, to replace common names with the scientific names
#first standardising all the names in the catch data
estuary_catch_log_clean2 <- estuary_catch_log_clean |>
  mutate(
    species = str_to_lower(str_trim(species)),
    species = str_replace_all(species, " ", "_")
  )
#reading in the species dictionary
species_dictionary <- read_csv("../data/workshop2/species_dictionary.csv")

#adding the scientific names to the catch data using left join - will now include both scientific and common names in the catch data
estuary_catch_log_clean2 <- estuary_catch_log_clean2 |>
  mutate(common_name = species) |>
  left_join(species_dictionary, by = join_by(common_name))

#combining the catch data with the summarised sonde data using a left join into 1 master data frame 
master_data <- estuary_catch_log_clean2 |>
  left_join(summarised_sonde, by = join_by(site, date))

#Phase 3
#using tidyr:complete to build a zero data framework, to ensure every species is represented at every site on every sampling day 
zero_data_framework <- master_data |>
  complete(site, date, scientific_name, fill = list(count = 0))
#replacing these new NA values in the catch column with 0 using coalesce()
final_dataset <- zero_data_framework |>
  mutate(count = coalesce(count, 0))

#Phase 4
#using final dataset to generate a summary table showing mean standard error on fish catch and salinity for each scientific species across each estuary zone 
master_summary <- final_dataset |>
  group_by(site, scientific_name) |>
  summarise(mean_count = mean(count, na.rm = TRUE),
            se_count = sd(count, na.rm = TRUE) / sqrt(n()),
            mean_salinity = mean(mean_salinity, na.rm = TRUE),
            se_salinity = sd(mean_salinity, na.rm = TRUE) / sqrt(n()),
            .groups = "drop")

#Phase 5 - Visual Communication 
#visualing how different species change along salinity gradient with a multi-panel plot using ggplot2 and facet_wrap()
master_summary |> 
  ggplot(aes(x = site, y = mean_count, fill = scientific_name)) +
  geom_line(group = 1) +
  # add in points from master data
  geom_point(data = final_dataset, aes(x = site, y = count),
             position = position_jitter(width = 0.2), alpha = 0.2, size = 1, inherit.aes = FALSE) + 
  geom_point(position = "dodge", size = 4, pch = 23) +
  # SE pretty narrow, potentially not worth plotting but let's viewer see that included
  geom_errorbar(aes(ymin = mean_count - se_count, ymax = mean_count + se_count), 
                position = position_dodge(0.9), width = 0.2) + 
  facet_wrap(~ scientific_name, scales = "fixed") +
  theme_minimal() +
  theme(
    strip.text = element_text(face = "italic", size = 10, colour = "grey20"), # spp names in italic
   # legend.position = "bottom"
    legend.position = "none" # legend unnecessary
  ) +
  labs(
    #title = "Predatory Fish Abundance across Estuarine Salinity Gradients", # default ggplot title appears on top
    #subtitle = "Ross River Estuary System, May 2026",
    x = "Spatial Zone",
    # scientific label for y axis of n day -1 use regex to get superscript
    y = expression("Abundance (n day"^-1*")"),
  #  y = "Daily abundance (n day^-1)"
    y = "Abundance (per day)"
  )
```



